name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev libpthread-stubs0-dev lcov
        pip install --user cpp-coveralls
        cd /usr/src/googletest
        sudo cmake .
        sudo make
    - name: Build tests
      run: |
        make test

    - name: Execute tests
      run: |
        ./test-lgo

    - name: Build project
      run: make all

    - name: Generate Coverage Data
      run: |
        make coverage

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: html_coverage/coverage.info

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup environment for lint
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy

    - name: Run Clang-Tidy
      run: make lint

